#!/bin/zsh
[[ -z "$1" ]] && echo "seacurli [url file]{,.url}" && return

backwhat(){
        [[ -f "$1.url" ]] && 1="$1.url"
        echo wget -O "${1:t:r}" -i "${1}"
}

for ARG in "$@"
do
        RUN=$(backwhat $ARG)
        echo $RUN
        eval $RUN
done
